//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Rents = new HashSet<Rent>();
            this.Reviews = new HashSet<Review>();
            this.WaitingLists = new HashSet<WaitingList>();
        }
    
        public int MemberID { get; set; }
        public byte MemberLevel { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public Nullable<short> HouseNumber { get; set; }
        public Nullable<int> HomePhone { get; set; }
        public int MobilePhone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public short DaysBalance { get; set; }
        public System.DateTime MemberSince { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingList> WaitingLists { get; set; }
    }
}
