//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.Rents = new HashSet<Rent>();
            this.Reviews = new HashSet<Review>();
            this.WaitingLists = new HashSet<WaitingList>();
            this.Actors = new HashSet<Actor>();
        }
    
        public string MovieID { get; set; }
        public string MovieName { get; set; }
        public short MovieTypeID { get; set; }
        public short Copies { get; set; }
        public string Summary { get; set; }
        public short Year { get; set; }
        public short Lenght { get; set; }
        public short CountryID { get; set; }
        public string MoviePicUrl { get; set; }
        public string TrailerUrl { get; set; }
        public byte Active { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual MovieType MovieType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WaitingList> WaitingLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actors { get; set; }
    }
}
