//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Actor
{
    public Actor()
    {
        this.Movies = new HashSet<Movie>();
    }

    public int ActorID { get; set; }
    public string ActorName { get; set; }
    public System.DateTime BirthDate { get; set; }
    public Nullable<short> CountryID { get; set; }

    public virtual Country Country { get; set; }
    public virtual ICollection<Movie> Movies { get; set; }
}

public partial class Country
{
    public Country()
    {
        this.Actors = new HashSet<Actor>();
        this.Movies = new HashSet<Movie>();
    }

    public short CountryID { get; set; }
    public string CountryName { get; set; }

    public virtual ICollection<Actor> Actors { get; set; }
    public virtual ICollection<Movie> Movies { get; set; }
}

public partial class Member
{
    public Member()
    {
        this.Rents = new HashSet<Rent>();
        this.Reviews = new HashSet<Review>();
        this.WaitingLists = new HashSet<WaitingList>();
    }

    public int MemberID { get; set; }
    public byte MemberLevel { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int ID { get; set; }
    public Nullable<System.DateTime> BirthDate { get; set; }
    public string Street { get; set; }
    public string City { get; set; }
    public Nullable<short> HouseNumber { get; set; }
    public Nullable<int> HomePhone { get; set; }
    public int MobilePhone { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public short DaysBalance { get; set; }
    public System.DateTime MemberSince { get; set; }

    public virtual ICollection<Rent> Rents { get; set; }
    public virtual ICollection<Review> Reviews { get; set; }
    public virtual ICollection<WaitingList> WaitingLists { get; set; }
}

public partial class Movie
{
    public Movie()
    {
        this.Rents = new HashSet<Rent>();
        this.Reviews = new HashSet<Review>();
        this.WaitingLists = new HashSet<WaitingList>();
        this.Actors = new HashSet<Actor>();
    }

    public string MovieID { get; set; }
    public string MovieName { get; set; }
    public short MovieTypeID { get; set; }
    public short Copies { get; set; }
    public string Summary { get; set; }
    public short Year { get; set; }
    public short Lenght { get; set; }
    public short CountryID { get; set; }
    public string MoviePicUrl { get; set; }
    public string TrailerUrl { get; set; }
    public byte Active { get; set; }
    public System.DateTime DateAdded { get; set; }

    public virtual Country Country { get; set; }
    public virtual MovieType MovieType { get; set; }
    public virtual ICollection<Rent> Rents { get; set; }
    public virtual ICollection<Review> Reviews { get; set; }
    public virtual ICollection<WaitingList> WaitingLists { get; set; }
    public virtual ICollection<Actor> Actors { get; set; }
}

public partial class MovieType
{
    public MovieType()
    {
        this.Movies = new HashSet<Movie>();
    }

    public short MovieTypeID { get; set; }
    public string MovieTypeName { get; set; }

    public virtual ICollection<Movie> Movies { get; set; }
}

public partial class popular
{
    public string MovieID { get; set; }
    public Nullable<int> movieCount { get; set; }
}

public partial class Rent
{
    public int MemberID { get; set; }
    public string MovieID { get; set; }
    public System.DateTime RentStart { get; set; }
    public Nullable<System.DateTime> RentEnd { get; set; }
    public Nullable<int> RentDays { get; set; }

    public virtual Member Member { get; set; }
    public virtual Movie Movie { get; set; }
}

public partial class Review
{
    public int MemberID { get; set; }
    public string MovieID { get; set; }
    public string ReviewText { get; set; }
    public byte Rate { get; set; }
    public Nullable<System.DateTime> ReviewDate { get; set; }

    public virtual Member Member { get; set; }
    public virtual Movie Movie { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class WaitingList
{
    public int MemberID { get; set; }
    public string MovieID { get; set; }
    public System.DateTime WaitDate { get; set; }

    public virtual Member Member { get; set; }
    public virtual Movie Movie { get; set; }
}
